---
version: '3'
services:

# START SERVICE image.wrapper
  image:
    image: ${VCWC_REGISTRY}${VCWC_REALM_RUNTIME}/vcwc.${VCWC_DC_GLOBAL_IMAGE_NAME} 
    environment: []
    command: ['sleep 0.5']
    volumes: []
    ports: []
    networks: []
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '128m'
        reservations:
          memory: '5m'
${VCWC_DC_IMAGE_WRAPPER_COMPOSE_EXTENSIONS}
# END SERVICE image.wrapper

networks: {${VCWC_DC_GLOBAL_NETWORKS}}
volumes: {${VCWC_DC_GLOBAL_VOLUMES}}
${VCWC_DC_GLOBAL_COMPOSE_EXTENSIONS}
