---
version: '3'
services:

# START SERVICE image.wrapper
  image:
    image: ${VWC_REGISTRY}${VWC_REALM_RUNTIME}/vcwc.${VWC_DC_GLOBAL_IMAGE_NAME} 
    environment: []
    command: ['sleep 0.5']
    volumes: []
    ports: []
    networks: []
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '128m'
        reservations:
          memory: '5m'
${VWC_DC_IMAGE_WRAPPER_COMPOSE_EXTENSIONS}
# END SERVICE image.wrapper

networks: {${VWC_DC_GLOBAL_NETWORKS}}
volumes: {${VWC_DC_GLOBAL_VOLUMES}}
${VWC_DC_GLOBAL_COMPOSE_EXTENSIONS}
